"""It won't work

Revision ID: 10996f7afe1c
Revises: 5ca4b010eb5e
Create Date: 2025-12-20 16:39:36.791260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10996f7afe1c'
down_revision: Union[str, Sequence[str], None] = '5ca4b010eb5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('movies', sa.Column('author_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'movies', 'authors', ['author_id'], ['id'])
    op.add_column('series', sa.Column('author_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'series', 'authors', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'series', type_='foreignkey')
    op.drop_column('series', 'author_id')
    op.drop_constraint(None, 'movies', type_='foreignkey')
    op.drop_column('movies', 'author_id')
    op.drop_table('authors')
    # ### end Alembic commands ###
