"""Created email for users + deleted username

Revision ID: b8b4e8ceb463
Revises: 8cbe6eebdc84
Create Date: 2025-12-25 12:46:05.871136

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b8b4e8ceb463"
down_revision: Union[str, Sequence[str], None] = "8cbe6eebdc84"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("email", sa.String(length=25), nullable=False))
    op.alter_column(
        "users",
        "hashed_password",
        existing_type=postgresql.BYTEA(),
        type_=sa.String(length=255),
        existing_nullable=False,
    )
    op.create_unique_constraint(None, "users", ["email"])
    op.create_unique_constraint(None, "users", ["visible_name"])
    op.drop_column("users", "username")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("username", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "users", type_="unique")
    op.drop_constraint(None, "users", type_="unique")
    op.alter_column(
        "users",
        "hashed_password",
        existing_type=sa.String(length=255),
        type_=postgresql.BYTEA(),
        existing_nullable=False,
    )
    op.drop_column("users", "email")
    # ### end Alembic commands ###
