"""Series

Revision ID: 5ca4b010eb5e
Revises: 0f340a87ed16
Create Date: 2025-12-20 16:27:10.087205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ca4b010eb5e'
down_revision: Union[str, Sequence[str], None] = '0f340a87ed16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('series',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('episodes', sa.Integer(), nullable=False),
    sa.Column('seasons', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('genre', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('movies', 'genre',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'genre',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_table('series')
    # ### end Alembic commands ###
