"""empty message

Revision ID: 1707f3d646a3
Revises: ebbdb20f8091
Create Date: 2026-01-16 10:45:27.829087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1707f3d646a3'
down_revision: Union[str, Sequence[str], None] = 'ebbdb20f8091'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('series', sa.Column('year_of_issue', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('series', 'year_of_issue')
    # ### end Alembic commands ###
